name: ci
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  TURBO_API: 'http://127.0.0.1:9080'
  TURBO_TOKEN: ${{ secrets.TURBO_SERVER_TOKEN }}
  TURBO_TEAM: ${{ github.repository_owner }}

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 7.0.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: 📀 Install dependencies
        run: pnpm install

      - name: Setup a local cache server for Turborepo
        uses: felixmosh/turborepo-gh-artifacts@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          server-token: ${{ secrets.TURBO_SERVER_TOKEN }}

      - name: 🧹 Lint and Test
        run: pnpm turbo lint check coverage --color

      - name: ⏫ Upload coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 👷‍♀️ Build
        run: pnpm turbo build --color --concurrency=5

      - name: ⏫ Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            build
